### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by johnnymdoubleu** [johnnymdoubleu/lassoSSNAL#7]
---
Checklist for Code Development
---

### Classic Lasso

- [ ] Classic_Lasso_SSNAL.m **(On going)** - 22nd Nov
- [ ] Classic_Lasso_SSNAL_Wrapper.m
- [ ] Classic_Lasso_SSNAL_main.m **(On going)** - 22nd Nov
- [ ] Classic_Lasso_SSNCG.m
- [ ] Classic_Lasso_linsys_solver.m
- [ ] matvec_ClassicLasso.m
- [ ] matvec_ClassicLasso_Amap.m

### Solvers

- [ ] findnnz.m (Completed) - 22nd Nov
- [ ] mychol.m (using `chol()` in R) - 22nd Nov
- [ ] mylinsysolve.m (using `solve()` in R) - 22nd Nov
- [ ] proj_inf.m (Completed) - 22nd Nov
- [ ] proxL1.m (Completed) - 22nd Nov
